### PR TITLE
Fetcher base + BabelNet configurations and libraries

### PR DESCRIPTION
**Pull request by CL124C41A**

### CODE REVIEW

**Comment by simonepri** [comment]
@CL124C41A Travis is now passing 😄

**Comment by CL124C41A** [comment]
@simonepri GJ, codecov tests are failing tho... it's normal since BabelNet tests are commented out (we cannot upload a working key to the repository), and we just need to get around it.

**Comment by simonepri** [comment]
LGTM can we merge?

**Comment by simonepri** [comment]
@DS98 @LucaPierfederici in order to test those remote services we need to mock it.
We need to use libraries like this:
http://site.mockito.org/

**Comment by simonepri** [comment]
@CL124C41A can we merge? Are you still working on that?

**Comment by CL124C41A** [comment]
@simonepri I'm done here, go on

**Pull request merged**
